<?xml version="1.0"?>
<package format="3">
  <name>followingbot_bridge</name>
  <version>0.0.0</version>
  <description>Serial bridge for followingbot Arduino Due state</description>
  <maintainer email="pyb54736905@gmail.com">parkmingwan</maintainer>
  <license>TODO: License declaration</license>

  <!-- 🔥 핵심 추가 -->
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <exec_depend>python3-serial</exec_depend>
  
  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
