<?xml version="1.0"?>
<package format="3">
  <name>followingbot_bringup</name>
  <version>0.0.0</version>
  <description>Bringup package for followingbot system</description>

  <maintainer email="parkmingwan@example.com">parkmingwan</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>followingbot_bridge</exec_depend>
  <exec_depend>followingbot_control</exec_depend>
  <exec_depend>followingbot_dwa</exec_depend>
  <exec_depend>sllidar_ros2</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>