<?xml version="1.0"?>
<package format="3">
  <name>followingbot_dwa</name>
  <version>0.0.0</version>
  <description>DWA-based obstacle avoidance with UWB + LiDAR sensor fusion</description>
  <maintainer email="pyb54736905@gmail.com">parkmingwan</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <exec_depend>python3-numpy</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
